site_name: AI邦娃遗迹
site_description: AI邦娃
site_author: Shuixin
site_url: https://shuixin-xdu.github.io/ 

# 主题配置
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 浅色模式
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: 深色模式

# 扩展
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# 导航
nav:
  - 首页: index.md
  - 角色图鉴: 
    - 图鉴: contents/characters.md
    - Anon犬: contents/characters/anon_dog.md
  - 素材图库: contents/assets/assets.md
  - 爱向视频: contents/part_gentle/gentle_videos.md
  - 虐向视频: contents/part_violent/violent_videos.md
  - 一般/剧情向视频: 
    - 一般向: contents/part_normal/normal_videos.md
    - nv0: contents/part_normal/videos/nv0/nv0.md
  - 猎奇专区: contents/part_bizaree/bizarre.md

# 页脚
extra:
  generator: false  # 隐藏"Powered by MkDocs"
